#!/usr/bin/env bash
# agent-orchestrator worker — invoked by daemon.py with env vars.
# Creates a git worktree, runs Aider against the LiteLLM proxy, pushes
# the branch, and opens a PR. Exits non-zero on any failure.
set -euo pipefail

: "${REPO:?REPO required}"
: "${ISSUE_NUMBER:?ISSUE_NUMBER required}"
: "${ISSUE_TITLE:?ISSUE_TITLE required}"
: "${WORKSPACE_ROOT:?WORKSPACE_ROOT required}"
: "${MODEL:?MODEL required}"
: "${LITELLM_BASE:?LITELLM_BASE required}"
ISSUE_BODY="${ISSUE_BODY:-}"
BRANCH_PREFIX="${BRANCH_PREFIX:-agent}"

REPO_NAME="${REPO##*/}"
BARE_DIR="$WORKSPACE_ROOT/repos/$REPO_NAME.git"
WORKSPACE="$WORKSPACE_ROOT/workspaces/$REPO_NAME/$ISSUE_NUMBER"
BRANCH="$BRANCH_PREFIX/issue-$ISSUE_NUMBER"

mkdir -p "$WORKSPACE_ROOT/repos" "$WORKSPACE_ROOT/workspaces/$REPO_NAME"

if [[ ! -d "$BARE_DIR" ]]; then
  echo "[worker] cloning bare $REPO -> $BARE_DIR"
  git clone --bare "https://github.com/$REPO.git" "$BARE_DIR"
fi
git -C "$BARE_DIR" fetch --prune origin

if [[ -d "$WORKSPACE" ]]; then
  echo "[worker] removing stale worktree at $WORKSPACE"
  git -C "$BARE_DIR" worktree remove --force "$WORKSPACE" 2>/dev/null || rm -rf "$WORKSPACE"
fi

DEFAULT_BRANCH="$(git -C "$BARE_DIR" symbolic-ref --short refs/remotes/origin/HEAD | sed 's|^origin/||')"
git -C "$BARE_DIR" worktree add -B "$BRANCH" "$WORKSPACE" "origin/$DEFAULT_BRANCH"

PROMPT_FILE="$(mktemp)"
trap 'rm -f "$PROMPT_FILE"' EXIT
cat >"$PROMPT_FILE" <<EOF
You are working on GitHub issue #$ISSUE_NUMBER in $REPO.

Title: $ISSUE_TITLE

Body:
$ISSUE_BODY

Constraints:
- Make focused changes that close the issue.
- Do not push or merge to the default branch.
- Commit your work; the surrounding harness will push and open a PR.
EOF

export OPENAI_API_BASE="$LITELLM_BASE"
export OPENAI_API_KEY="${OPENAI_API_KEY:-litellm-proxy}"

cd "$WORKSPACE"
aider \
  --model "$MODEL" \
  --message-file "$PROMPT_FILE" \
  --yes-always \
  --no-auto-test \
  --no-show-model-warnings \
  --no-analytics

if [[ -z "$(git log "origin/$DEFAULT_BRANCH..$BRANCH" --oneline)" ]]; then
  echo "[worker] aider produced no commits on $BRANCH" >&2
  exit 3
fi

git push -u origin "$BRANCH"

PR_BODY="Closes #$ISSUE_NUMBER

Generated by agent-orchestrator using model: \`$MODEL\`."
gh pr create \
  --repo "$REPO" \
  --base "$DEFAULT_BRANCH" \
  --head "$BRANCH" \
  --title "$ISSUE_TITLE" \
  --body "$PR_BODY"
